CREATE TYPE ASTRONOMICAL_OBJECT_TYPE AS ENUM ('Planet', 'Star');

CREATE TABLE SPACESHIP
(
    ID        SERIAL PRIMARY KEY,
    NAME      varchar(25) NOT NULL,
    MAX_SPEED integer     NOT NULL
);

CREATE TABLE SPACESHIP_ROOM
(
    ID           SERIAL PRIMARY KEY,
    BODY_NUMBER  integer NOT NULL,
    ROOM_NUMBER  integer NOT NULL,
    SPACESHIP_ID integer NOT NULL REFERENCES SPACESHIP ON DELETE CASCADE
);

CREATE TABLE HUMAN
(
    ID                SERIAL PRIMARY KEY,
    NAME              varchar(25) NOT NULL,
    SPACESHIP_ROOM_ID integer     NOT NULL REFERENCES SPACESHIP_ROOM ON DELETE CASCADE
);

CREATE TABLE GALAXY
(
    ID   SERIAL PRIMARY KEY,
    NAME varchar(25) NOT NULL,
    SIZE integer     NOT NULL CHECK ( SIZE > 0
        )
);

CREATE TABLE PLANETARY_SYSTEM
(
    ID        SERIAL PRIMARY KEY,
    NAME      varchar(25) NOT NULL,
    GALAXY_ID integer REFERENCES GALAXY ON DELETE CASCADE
);

CREATE TABLE ASTRONOMICAL_OBJECT
(
    ID                  SERIAL PRIMARY KEY,
    TYPE                ASTRONOMICAL_OBJECT_TYPE NOT NULL,
    NAME                varchar(25)              NOT NULL,
    COLOR               varchar(25)              NOT NULL,
    SIZE                integer                  NOT NULL CHECK ( SIZE > 0
        ),
    PLANETARY_SYSTEM_ID integer                  NOT NULL REFERENCES PLANETARY_SYSTEM ON DELETE CASCADE
);

CREATE TABLE VISITED_PLANETARY_SYSTEM
(
    SPACESHIP_ID        integer NOT NULL REFERENCES SPACESHIP ON DELETE CASCADE,
    PLANETARY_SYSTEM_ID integer NOT NULL REFERENCES PLANETARY_SYSTEM ON DELETE CASCADE,
    PRIMARY KEY (SPACESHIP_ID, PLANETARY_SYSTEM_ID)
);