name: Upload

on:
  push:
    branches: [ "main" ]

jobs:
  upload-to-helios:
    runs-on: ubuntu-latest
    name: Upload files to Helios
    steps:
      - uses: actions/checkout@v3

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HELIOS_HOST }}
          username: ${{ secrets.HELIOS_USERNAME }}
          password: ${{ secrets.HELIOS_PASSWORD }}
          port: ${{ secrets.HELIOS_PORT }}
          script: whoami

      - name: Copy files with SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HELIOS_HOST }}
          username: ${{ secrets.HELIOS_USERNAME }}
          password: ${{ secrets.HELIOS_PASSWORD }}
          port: ${{ secrets.HELIOS_PORT }}
          source: "SQL"
          target: "/home/studs/s311703/databases-lab1"
          debug: true
